# GENERAL SPECIFICATIONS
Real_Time: False
Run_on_Jetson: False

#DEBUG
debug_mode: False
view_video: False
draw_reg: False

#MODEL SPECIFICATIONS
scale: 0.03912 #0.03757452 #0.03912 #0.03805#0.0378047581618546 #0.0376047581618546  #scale = 0.019390745853434508
file_path_control_points: './full_outer.csv'
file_path_model: 'full_outer_inner_part_only.ply'
file_path_tread: 'full_outer_treads_part_only.ply'
inner_to_outer: 'inner_to_outer_correspondences.npy'
inner_to_treads: 'inner_to_treads_correspondences.npy'

#IMAGE_STREAM
RGB_D_folder: 'realsense2' #'../DATA/unseated_slow_1_d3_c18' #'../../DATA/temporal_cleat_over_test_eg_horizontal_10mm_disp_no_slip_d0_c0' #'realsense2' #'test1' #'realsense2' #'../../DATA/test_eg_horizontal_10mm_disp_no_slip_d0_c0' # 'realsense2'
image_depth_profile: 3 #3
image_color_profile: 18 #18
start_index: 157 #150 #100

#CAMERA SETTINGS
cam_depth_profile: 3 
cam_color_profile: 18 
exposure: 3000 #21000
gain: 220 #20

#OPTICAL FLOW PARAMS
opt_method: 'dense' #'dense' #'sparse'
dense_method: 'farne' #'farne' #'brox' 'pyrLK' 'dual'
sparse_step: 50